### ISSUE TITLE
Example walkthrough for assembly would be helpful

### ISSUE THREAD

**Issue by schmeing** [Christina-hshi/SH-assembly#3]
Hi,
having an example of an assembly in the README would be very helpful, ideally with comments on how to choose the parameters. As a suggestion you could present how you created the two assemblies in the publication (I might have missed it, but I did not find the parameters used in the publication itself except k=47).

**Comment by Christina-hshi** [comment]
Hi Schmeing,
Thank you for your suggestion! I will prepare a README with more details ASAP!

**Comment by Christina-hshi** [comment]
Hi Schmeing, 
I have added more details with examples in the README. Thanks for your suggestion!
