### ISSUE TITLE
Error when make -- tbb/concurrent_unordered_set.h: No such file or directory

### ISSUE THREAD

**Issue by sanvva** [Christina-hshi/SH-assembly#6]
[https://github.com/Christina-hshi/SH-assembly/issues/5](url)

conda install -c conda-forge tbb=2020.3

[ 14%] Building CXX object cqf/CMakeFiles/cqf-core-objs.dir/true2falseKmer_DP.cpp.o
In file included from /home/hzs/bin/02Assembly/SH-assembly/cqf/true2falseKmer_DP.h:12,
                 from /home/hzs/bin/02Assembly/SH-assembly/cqf/true2falseKmer_DP.cpp:10:
/home/hzs/bin/02Assembly/SH-assembly/base/global.h:59:10: fatal error: tbb/concurrent_unordered_set.h: No such file or directory
   59 | #include <tbb/concurrent_unordered_set.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [cqf/CMakeFiles/cqf-core-objs.dir/build.make:96: cqf/CMakeFiles/cqf-core-objs.dir/true2falseKmer_DP.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:323: cqf/CMakeFiles/cqf-core-objs.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

**Comment by Christina-hshi** [comment]
`
tbb/concurrent_unordered_set.h: No such file or directory
`
The compiler could not find the **tbb header file**. For C/C++ libraries installed (using conda, manually, or else) under non system default directory, you need to manually set up the paths such that the compiler/linker can find them. 
Please try setting environment variables, including **C_INCLUDE_PATH** and **CPLUS_INCLUDE_PATH**. To further avoid "**not found**" errors during linking, you may also want to set **LD_LIBRARY_PATH** and **LIBRARY_PATH** as well. 
Please refer to https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_23.html for explanation of the these environmental variables.

**Comment by sanvva** [comment]
> `tbb/concurrent_unordered_set.h: No such file or directory`
> The compiler could not find the **tbb header file**. For C/C++ libraries installed (using conda, manually, or else) under non system default directory, you need to manually set up the paths such that the compiler/linker can find them.
> Please try setting environment variables, including **C_INCLUDE_PATH** and **CPLUS_INCLUDE_PATH**. To further avoid "**not found**" errors during linking, you may also want to set **LD_LIBRARY_PATH** and **LIBRARY_PATH** as well.
> Please refer to https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_23.html for explanation of the these environmental variables.

Where are the tbb header files when installed by conda?

**Comment by Christina-hshi** [comment]
Usually under "**\<path to conda>/include**" for **base** environment, and "**\<path to conda>/\<environment>/include**" for other conda environments.

**Comment by sanvva** [comment]
> Usually under "**<path to conda>/include**" for **base** environment, and "**<path to conda>/<environment>/include**" for other conda environments.

Thanks! But I cannot find **concurrent_unordered_set.h** under **~/miniconda3/include**. 
```
export C_INCLUDE_PATH=~/user/miniconda3/include
export CPLUS_INCLUDE_PATH=~/user/miniconda3/include
export LD_LIBRARY_PATH=~/user/miniconda3/lib
export LIBRARY_PATH=~/user/miniconda3/lib
```
Same error still occurs.
Does it need to "`conda install tbb-devel=2020.3`"? But I cannot find a resource to intall tab-devel 2020.3.

**Comment by sanvva** [comment]
> > Usually under "**/include**" for **base** environment, and "**//include**" for other conda environments.
> 
> Thanks! But I cannot find **concurrent_unordered_set.h** under **~/miniconda3/include**.
> 
> ```
> export C_INCLUDE_PATH=~/user/miniconda3/include
> export CPLUS_INCLUDE_PATH=~/user/miniconda3/include
> export LD_LIBRARY_PATH=~/user/miniconda3/lib
> export LIBRARY_PATH=~/user/miniconda3/lib
> ```
> 
> Same error still occurs. Does it need to "`conda install tbb-devel=2020.3`"? But I cannot find a resource to intall tab-devel 2020.3.

Yes, I succeeded.
